export const ADMIN_NAV_LINKS = [
  { label: 'Dashboard', path: '/admin', icon: 'LayoutDashboard' },
  { label: 'Empresas', path: '/admin/empresas', icon: 'Store' },
  { label: 'Usuários', path: '/admin/usuarios', icon: 'Users' },
  { label: 'Categorias', path: '/admin/categorias', icon: 'FolderTree' },
  { label: 'Tipos', path: '/admin/tipos-estabelecimento', icon: 'Building2' },
  { label: 'Tags', path: '/admin/tags', icon: 'Tags' },
  { label: 'Comissões', path: '/admin/comissoes', icon: 'Percent' },
  { label: 'Motoboys', path: '/admin/motoboys', icon: 'Bike' },
  { label: 'Planos', path: '/admin/planos', icon: 'CreditCard' },
  { label: 'Marketplace', path: '/admin/marketplace-boost', icon: 'Megaphone' },
  { label: 'Aparência', path: '/admin/aparencia', icon: 'Palette' },
  { label: 'Configurações', path: '/admin/configuracoes', icon: 'Settings' },
  { label: 'Meu Perfil', path: '/admin/meu-perfil', icon: 'UserCircle' },
];
