-- Catálogo amplo de tipos de estabelecimento — cobre MEIs, pequenos negócios,
-- comércio, alimentação, serviços e empresas locais pro cadastro em
-- /admin/tipos-estabelecimento. Idempotente (ON CONFLICT em name, que já é
-- UNIQUE desde 20260713000001_establishment_types.sql) — os 3 tipos seedados
-- naquela migration (Restaurante, Farmácia, Material de Construção) aparecem
-- de novo aqui só pra manter a lista de origem completa, o conflito é ignorado.
INSERT INTO public.establishment_types (name, icon_name)
VALUES
    -- Comércio e varejo
    ('Farmácia', 'Pill'),
    ('Drogaria', 'Pill'),
    ('Perfumaria', 'SprayCan'),
    ('Loja de cosméticos', 'Sparkles'),
    ('Loja de roupas', 'Shirt'),
    ('Loja de calçados', 'Footprints'),
    ('Loja de bolsas e acessórios', 'ShoppingBag'),
    ('Loja de moda infantil', 'Baby'),
    ('Loja de moda íntima', 'Shirt'),
    ('Loja de roupas esportivas', 'Dumbbell'),
    ('Loja de eletrônicos', 'Smartphone'),
    ('Loja de celulares', 'Smartphone'),
    ('Assistência técnica de celulares', 'Wrench'),
    ('Loja de informática', 'Laptop'),
    ('Assistência técnica de informática', 'Wrench'),
    ('Loja de acessórios para celular', 'Smartphone'),
    ('Loja de presentes', 'Gift'),
    ('Loja de brinquedos', 'ToyBrick'),
    ('Papelaria', 'BookOpen'),
    ('Bazar', 'Store'),
    ('Armarinho', 'Scissors'),
    ('Loja de tecidos', 'Shirt'),
    ('Loja de artigos para festas', 'PartyPopper'),
    ('Loja de artigos esportivos', 'Dumbbell'),
    ('Loja de instrumentos musicais', 'Music'),
    ('Loja de móveis', 'Sofa'),
    ('Loja de colchões', 'BedDouble'),
    ('Loja de eletrodomésticos', 'Refrigerator'),
    ('Loja de utilidades domésticas', 'Home'),
    ('Loja de decoração', 'Palette'),
    ('Loja de produtos naturais', 'Leaf'),
    ('Loja de suplementos', 'Dumbbell'),
    ('Loja de produtos religiosos', 'Church'),
    ('Loja de produtos para animais', 'PawPrint'),
    ('Pet Shop', 'PawPrint'),
    ('Agropecuária', 'Tractor'),
    ('Floricultura', 'Flower2'),
    ('Loja de plantas e jardinagem', 'Sprout'),
    ('Loja de ferramentas', 'Wrench'),
    ('Loja de materiais elétricos', 'Zap'),
    ('Loja de materiais hidráulicos', 'Droplet'),
    ('Material de Construção', 'HardHat'),
    ('Loja de tintas', 'PaintBucket'),
    ('Loja de ferragens', 'Hammer'),
    ('Loja de vidros', 'Frame'),
    ('Loja de iluminação', 'Lightbulb'),
    ('Loja de peças automotivas', 'Car'),
    ('Loja de pneus', 'Disc'),
    ('Loja de motos e peças', 'Bike'),
    ('Loja de bicicletas', 'Bike'),

    -- Alimentação
    ('Restaurante', 'UtensilsCrossed'),
    ('Lanchonete', 'Sandwich'),
    ('Hamburgueria', 'Beef'),
    ('Pizzaria', 'Pizza'),
    ('Açaíteria', 'IceCream2'),
    ('Sorveteria', 'IceCream'),
    ('Pastelaria', 'Croissant'),
    ('Tapiocaria', 'Cookie'),
    ('Cafeteria', 'Coffee'),
    ('Padaria', 'Croissant'),
    ('Confeitaria', 'Cake'),
    ('Doceria', 'Cookie'),
    ('Boleria', 'Cake'),
    ('Casa de salgados', 'Sandwich'),
    ('Marmitaria', 'Utensils'),
    ('Comida caseira', 'Utensils'),
    ('Restaurante japonês', 'Fish'),
    ('Restaurante italiano', 'ChefHat'),
    ('Restaurante árabe', 'UtensilsCrossed'),
    ('Restaurante vegetariano', 'Salad'),
    ('Restaurante vegano', 'Leaf'),
    ('Churrascaria', 'Beef'),
    ('Espetaria', 'Flame'),
    ('Peixaria', 'Fish'),
    ('Frango assado', 'Drumstick'),
    ('Casa de massas', 'UtensilsCrossed'),
    ('Creperia', 'Croissant'),
    ('Temakeria', 'Fish'),
    ('Delivery de comida', 'Truck'),
    ('Food Truck', 'Truck'),
    ('Buffet', 'UtensilsCrossed'),
    ('Cozinha industrial', 'ChefHat'),
    ('Açougue', 'Beef'),
    ('Peixaria e frutos do mar', 'Fish'),
    ('Hortifruti', 'Carrot'),
    ('Mercado', 'ShoppingCart'),
    ('Supermercado', 'ShoppingCart'),
    ('Minimercado', 'ShoppingCart'),
    ('Mercearia', 'ShoppingBasket'),
    ('Conveniência', 'Store'),

    -- Beleza e cuidados pessoais
    ('Salão de beleza', 'Scissors'),
    ('Barbearia', 'Scissors'),
    ('Cabeleireiro', 'Scissors'),
    ('Manicure e pedicure', 'Hand'),
    ('Designer de sobrancelhas', 'Eye'),
    ('Esteticista', 'Sparkles'),
    ('Clínica de estética', 'Sparkles'),
    ('Depilação', 'Sparkles'),
    ('Maquiador(a)', 'Palette'),
    ('Massoterapia', 'Heart'),
    ('Spa', 'Flower2'),
    ('Podologia', 'Footprints'),
    ('Bronzeamento', 'Sun'),
    ('Alongamento de unhas', 'Hand'),
    ('Lash Designer', 'Eye'),
    ('Trancista', 'Scissors'),
    ('Dreadmaker', 'Scissors'),
    ('Tatuagem e piercing', 'PenTool'),

    -- Serviços e manutenção
    ('Eletricista', 'Zap'),
    ('Encanador', 'Droplet'),
    ('Pedreiro', 'HardHat'),
    ('Pintor', 'PaintBucket'),
    ('Gesseiro', 'HardHat'),
    ('Serralheiro', 'Hammer'),
    ('Marceneiro', 'Hammer'),
    ('Carpinteiro', 'Hammer'),
    ('Vidraceiro', 'Frame'),
    ('Instalador de ar-condicionado', 'Wind'),
    ('Técnico de refrigeração', 'Snowflake'),
    ('Manutenção de eletrodomésticos', 'Wrench'),
    ('Manutenção de máquinas', 'Wrench'),
    ('Chaveiro', 'KeyRound'),
    ('Dedetização', 'Bug'),
    ('Limpeza residencial', 'SprayCan'),
    ('Limpeza comercial', 'SprayCan'),
    ('Lavanderia', 'WashingMachine'),
    ('Costureira', 'Scissors'),
    ('Alfaiataria', 'Shirt'),
    ('Sapateiro', 'Footprints'),
    ('Tapeçaria', 'Sofa'),
    ('Estofador', 'Sofa'),
    ('Jardinagem', 'Sprout'),
    ('Paisagismo', 'TreePine'),
    ('Fotógrafo', 'Camera'),
    ('Filmagem e produção audiovisual', 'Video'),
    ('Gráfica Rápida', 'Printer'),
    ('Comunicação visual', 'Palette'),
    ('Designer gráfico', 'PenTool'),
    ('Serigrafia', 'Printer'),
    ('Personalização de produtos', 'Gift'),

    -- Automotivo e transporte
    ('Oficina mecânica', 'Wrench'),
    ('Autoelétrica', 'Zap'),
    ('Borracharia', 'Disc'),
    ('Lava-jato', 'Droplets'),
    ('Estética automotiva', 'Sparkles'),
    ('Funilaria e pintura', 'PaintBucket'),
    ('Guincho', 'Truck'),
    ('Mototáxi', 'Bike'),
    ('Transporte de passageiros', 'Car'),
    ('Transporte de pequenas cargas', 'Truck'),

    -- Profissionais e empresas
    ('Contabilidade', 'Calculator'),
    ('Consultoria empresarial', 'Briefcase'),
    ('Agência de marketing', 'Megaphone'),
    ('Agência de publicidade', 'Megaphone'),
    ('Desenvolvimento de software', 'Code'),
    ('Suporte de informática', 'Laptop'),
    ('Design gráfico', 'PenTool'),
    ('Social Media', 'AtSign'),
    ('Agência de turismo', 'Plane'),
    ('Corretor de imóveis', 'Home'),
    ('Imobiliária', 'Building2'),
    ('Seguros', 'ShieldCheck'),
    ('Despachante', 'FileText'),
    ('Serviços administrativos', 'Briefcase'),
    ('Treinamentos e cursos', 'GraduationCap'),
    ('Escola particular', 'GraduationCap'),
    ('Curso profissionalizante', 'GraduationCap'),
    ('Fotocópias e impressão', 'Printer'),
    ('Serviços de digitação', 'Keyboard'),
    ('Correspondente bancário', 'Landmark'),

    -- Animais
    ('Banho e tosa', 'PawPrint'),
    ('Veterinário', 'Stethoscope'),
    ('Clínica veterinária', 'Stethoscope'),
    ('Hotel para animais', 'PawPrint'),
    ('Adestramento de animais', 'PawPrint'),
    ('Pet sitter', 'PawPrint'),
    ('Loja de ração', 'Bone'),

    -- Casa, construção e imóveis
    ('Arquitetura', 'Ruler'),
    ('Engenharia', 'HardHat'),
    ('Topografia', 'MapPin'),
    ('Design de interiores', 'Sofa'),
    ('Instalação de pisos', 'LayoutGrid'),
    ('Instalação de forros', 'LayoutGrid'),
    ('Instalação de portas e janelas', 'DoorOpen'),
    ('Reformas em geral', 'HardHat'),
    ('Construção civil', 'HardHat'),
    ('Aluguel de equipamentos', 'Package'),
    ('Materiais para construção', 'HardHat'),

    -- Serviços pessoais e família
    ('Creche', 'Baby'),
    ('Cuidador de idosos', 'Heart'),
    ('Babá', 'Baby'),
    ('Serviços para festas infantis', 'PartyPopper'),
    ('Recreação infantil', 'PartyPopper'),
    ('Organização de eventos', 'CalendarDays'),
    ('Cerimonial', 'PartyPopper'),
    ('Decoração de festas', 'PartyPopper'),
    ('Fotografia de eventos', 'Camera'),
    ('Aluguel de equipamentos para festas', 'PartyPopper'),

    -- Outros negócios locais
    ('Gráfica', 'Printer'),
    ('Distribuidora de bebidas', 'Wine'),
    ('Distribuidora de água', 'Droplets'),
    ('Gás de cozinha', 'Flame'),
    ('Loja de conveniência', 'Store'),
    ('Locadora de veículos', 'Car'),
    ('Locadora de equipamentos', 'Package'),
    ('Recarga de celular', 'Smartphone'),
    ('Reciclagem', 'Recycle'),
    ('Comércio de usados', 'Package'),
    ('Brechó', 'Shirt'),
    ('Sebo', 'BookOpen'),
    ('Antiquário', 'Archive'),
    ('Loja de produtos importados', 'Package'),
    ('Loja de produtos artesanais', 'Palette'),
    ('Artesanato', 'Palette'),
    ('Costura e ajustes', 'Scissors'),
    ('Fabricação de alimentos', 'ChefHat'),
    ('Produção de doces', 'Cake'),
    ('Produção de salgados', 'Sandwich')
ON CONFLICT (name) DO NOTHING;
